### PR TITLE
Quantum Leap in Gunicorn docs

### PR DESCRIPTION
**Pull request by daminichopra**
Updated docs on how to run quantum leap in gunicorn for [Issue](https://github.com/smartsdk/ngsi-timeseries-api/issues/360)

### CODE REVIEW

**Comment by daminichopra** [comment]
Hi @c0c0n3 @chicco785 , I have fixed the [wiki](https://github.com/smartsdk/ngsi-timeseries-api/wiki) part of document as mentioned in [Issue](https://github.com/smartsdk/ngsi-timeseries-api/issues/360) but i am unable to git clone its fork repository locally and raise PR for it separately. Please guide me if there is any approach to update fix for wiki part in Quantum Leap.

**Comment by c0c0n3** [comment]
hi @daminichopra 

> Please guide me if there is any approach to update fix for wiki part in Quantum Leap.

I wish I knew :-) It doesn't look like you can open a PR against the wiki :-( 
Not sure what to do, perhaps the easiest is for me to update the wiki after merging this PR.

Also, while this PR is a good start at documenting GUnicorn support, there's much more we should talk about in the docs, e.g. how to tune GUnicorn for QL which we'll only know after getting more prod experience with the upcoming `0.8` release. So it's best to hold off to complete the docs until then.

If you agree we could merge this PR but leave #360 open for now?

**Comment by daminichopra** [comment]
> hi @daminichopra
> 
> > Please guide me if there is any approach to update fix for wiki part in Quantum Leap.
> 
> I wish I knew :-) It doesn't look like you can open a PR against the wiki :-(
> Not sure what to do, perhaps the easiest is for me to update the wiki after merging this PR.
> 
> Also, while this PR is a good start at documenting GUnicorn support, there's much more we should talk about in the docs, e.g. how to tune GUnicorn for QL which we'll only know after getting more prod experience with the upcoming `0.8` release. So it's best to hold off to complete the docs until then.
> 
> If you agree we could merge this PR but leave #360 open for now?

Hi @c0c0n3 , Yes Please merge and close this PR. Also, I will see if i could find any approach to update wiki part in quantum leap. Thank you

**Comment by c0c0n3** [comment]
cool, thx alot!

**Review by c0c0n3 — APPROVED** [review]

**Pull request merged**
