### PR TITLE
WIP: Data migration from STH-Comet to QuantumLeap

### PR DESCRIPTION
**Pull request by pooja1pathak**
created dataMigration.md to describe about Migration tool which can be used to migrate data from STH-Comet to QL.

### CODE REVIEW

**Comment by taliaga** [comment]
Excellent, thank you very much!. The only missing thing is to refer this from the menu file [mkdocs.yml](https://github.com/smartsdk/ngsi-timeseries-api/blob/master/mkdocs.yml) after grafana so that the page is readable in the documentation. 

Don't worry about the build, we're having a look at the timeouts now. I'll take it from there.

**Comment by pooja1pathak** [comment]
Hi @taliaga, Thank you for the appreciation. 
My team is working on creation of new repository having same name as that of the tool.
I'll update you once it gets completed and will update menu file mkdocs.yml (as suggested by you) for reference to this document.
Till then I request you to not to merge this PR and also do not update any link for the same as the repository for this tool will be changed.

**Comment by pooja1pathak** [comment]
Hi @taliaga , I have updated the link for the tool in dataMigration.md and mkdocs.yml. 
You can merge this PR now.

**Comment by taliaga** [comment]
Thanks!

**Pull request merged**
