### PR TITLE
Fix for issue #225

### PR DESCRIPTION
**Pull request by pooja1pathak**
Fix for issue #225
Updated code to accept dateFrom and dateTo of API methods with quotes("").

### CODE REVIEW

**Comment by c0c0n3** [comment]
@pooja1pathak this is great thanks, except...most tests are failing. It looks like there's issues building the QL image, if you could please look into that :-)

**Comment by c0c0n3** [comment]
Also I'd like to propose an improvement. Can we move the strip stuff into a `parse_date` function which takes the string, strips any extra `"`, then attempts to convert to an actual Python date. Accordingly the translator should operate on date objects rather than strings. This way we avoid further grief if e.g. the date string is in a format we don't support. Also if in the future we decide to support more than one date format, we can just make the change in a single place, i.e. in `parse_date`.

This is just a suggestion. I'm actually already very happy with your submission. But just in case you have the time to do it...you know.

**Comment by pooja1pathak** [comment]
Hi @c0c0n3 , Thanks for the review :-)

I have updated the code as per your suggestion. Please review the updated PR.

**Comment by c0c0n3** [comment]
@pooja1pathak should I go ahead and merge into master?

**Comment by pooja1pathak** [comment]
Yes you can merge this PR :-)

**Pull request merged**
