### PR TITLE
Fix 125

### PR DESCRIPTION
**Pull request by c0c0n3**

### CODE REVIEW

**Comment by c0c0n3** [comment]
@chicco785 apparently it does, added a test to verify, see commit a0863f8

**Comment by chicco785** [comment]
LGTM

**Comment by chicco785** [comment]
given that this will go in the next release, i would wait @taliaga feedback before merge

**Comment by c0c0n3** [comment]
agreed :-)

**Comment by c0c0n3** [comment]
closes #125

**Pull request merged**
