### PR TITLE
Update README 

### PR DESCRIPTION
**Pull request by jason-fox**
Changes to follow [standard readme](https://github.com/RichardLitt/standard-readme) as recommended in the Contributor requirements

* Remove intro header
* Add link box
* Add ToC
* Standardize Section names
* Add license section

### CODE REVIEW

**Comment by c0c0n3** [comment]
Hi @jason-fox, this is great, thank you.
I'm not sure into which branch we should merge your patch though. I reckon this is a question for @taliaga : should it be `master`, `v0.6rc` or a new branch altogether?

The reason I mentioned creating a new branch is that then we could also work on #139 and #137 in that branch, and when done integrate the whole lot into the upcoming 0.6 release. In detail:

1. Create `docs` branch from `v0.6rc`.
2. Merge this PR into `docs`.
3. Fix #137 and #139 in the `docs` branch.
4. Merge `docs` into `v0.6rc`.

Thoughts?

**Comment by c0c0n3** [comment]
Oh forgot to mention. Ideally we should branch off `v0.6rc` after fixing #105 so that we won't sit with another PR whose builds fail for reasons that have nothing to do with the PR's actual code changes.

**Comment by taliaga** [comment]
Hi, let me do the docs branch to work on those issues and #133 as well. I'll start from Jason's changes. Let's keep it simple for now, I will merge this as it is, but I'll update the contribution guidelines to make it clear for future PR that it's better to branch off the next release's branch. Or at least, to say in future we'll be merging contributions to the release branch rather than to master; then we discuss who does the "rebasing".

**Comment by c0c0n3** [comment]
cool bananas!

**Pull request merged**
