### PR TITLE
Deleting dataMigration.md

### PR DESCRIPTION
**Pull request by iamarnavgarg**
The Data-Migration_tool repository will not be maintained in future and has been removed. Thus, deleting the reference of the tool from this main repository.

### CODE REVIEW

**Comment by c0c0n3** [comment]
hi @iamarnavgarg, why delete `dataMigration.md`? We updated it in master w/ a new section on migrating data from Crate to Timescale...we definitely need that info to be somewhere. Are you suggesting we should move those sections somewhere else? If so where?

**Comment by iamarnavgarg** [comment]
Hi @c0c0n3 I would like to inform you that @pooja1pathak would not be maintaining the GitHub repository any further. Also, the repository no longer exists. So, would kindly request you to please merge this PR asap.

Thanks

**Comment by c0c0n3** [comment]
@iamarnavgarg thanks for clarifying. Like I said, we can't merge this into master since there's a new section about Timescale in `dataMigration.md` which we'd like to keep. So rather than deleting this file, I suggest you:

1. undo the commit to delete the file
2. rebase `iamarnavgarg:iamarnavgarg-patch-1` on top of  `smartsdk:master`
3. edit the file to remove the whole section: "Migrating STH Comet data". Also please take care of removing any unused links at the bottom of the page.

Alternatively, I can do this myself, but then the easiest would be to close this PR **without merging**. Give me a shout if you'd rather go for this second option.

**Comment by iamarnavgarg** [comment]
Hi @c0c0n3,
I have reverted the commit and incorporated your suggested comments by just removing the "Migrating STH Comet data" sub-section. Now, would request you to please merge this PR asap.

Thanks

**Comment by chicco785** [comment]
can you rebase you branch on the remote master?

**Comment by iamarnavgarg** [comment]
> can you rebase you branch on the remote master?

Hi @chicco785, I have updated the branch.
Thanks

**Comment by c0c0n3** [comment]
@iamarnavgarg just merged into master, thank you so much for updating the docs! :-)

**Pull request merged**
