### PR TITLE
upgarded crate3.3.3 test env

### PR DESCRIPTION
**Pull request by daminichopra**
Upgraded crate test env to 3.3.3

### CODE REVIEW

**Comment by chicco785** [comment]
@daminichopra 4.x PR #300  integration is pending review, which will make this obsolete

**Comment by daminichopra** [comment]
Hi @chicco785 , As per my understanding there is no need to upgrade crate test env to 3.3.3 as 4.x integration is pending now.
I would like to suggest if you can merge this PR and then merge PR #300
Please confirm. Thanks

**Comment by c0c0n3** [comment]
Hi @daminichopra,

We just merged in #300, which brings support for Crate 4 and makes 3.3.5 available for testing backward compatibility:

https://github.com/smartsdk/ngsi-timeseries-api/pull/300/files#diff-ca4c6e6bba7e25458e0f4bb913efaadb

So unless you have any objections I'd drop these changes you've made and close this PR?

**Comment by daminichopra** [comment]
Hi @c0c0n3 , you can close this PR. Thank you

**Pull request closed without merging**
